import fs from "fs/promises";
import path from "path";
import { BrandAssets } from "@/config/brand-assets";
import { prisma } from "@/lib/prisma";

export class ProvisionService {
  /**
   * Clona a estrutura de pastas de um template base e injeta as variáveis de ambiente,
   * deixando-o pronto para um deploy ou execução local.
   * 
   * @param templateName Nome da pasta base em /templates
   * @param slug Identificador único do cliente/tenant
   */
  static async provisionLocalSite(templateName: string, slug: string, clientName: string) {
    console.log(`[PROVISION] Iniciando Setup para ${slug}...`);

    const rootDir = process.cwd();
    const templatePath = path.join(rootDir, "templates", templateName);
    const destinationPath = path.join(rootDir, "sites", slug);

    // 1. Verificar se o Template existe
    try {
      await fs.access(templatePath);
    } catch {
      throw new Error(`Template '${templateName}' não encontrado na pasta /templates.`);
    }

    // 2. Criar a pasta do novo Site (Clonagem)
    await fs.mkdir(destinationPath, { recursive: true });
    await fs.cp(templatePath, destinationPath, { recursive: true });
    console.log(`[PROVISION] Estrutura de arquivos do template clonada com sucesso.`);

    // 3. Cadastrar Tenant no Banco
    let tenant = await prisma.tenant.findUnique({ where: { slug } });
    if (!tenant) {
      tenant = await prisma.tenant.create({
        data: {
          name: clientName,
          slug,
          document: "Provisionado Localmente via Script"
        }
      });
      console.log(`[PROVISION] Tenant ${slug} registrado no Hub Central.`);
    }

    // 4. Injeção de Identidade Automatizada (Variáveis de Ambiente via script)
    const brandConfig = BrandAssets.norte;
    const envContent = `
# ==========================================
# ENV AUTO-GENERATED BY AGENCY OS PROVISIONER
# ==========================================
NEXT_PUBLIC_TENANT_ID=${tenant.id}
NEXT_PUBLIC_CLIENT_NAME="${clientName}"

# --- Brand Identity (Norte DNA) ---
NEXT_PUBLIC_THEME_PRIMARY=${brandConfig.colors.primary}
NEXT_PUBLIC_THEME_SECONDARY=${brandConfig.colors.secondary}
NEXT_PUBLIC_THEME_BACKGROUND=${brandConfig.colors.background}
NEXT_PUBLIC_AGENCY_LOGO=${brandConfig.logos.light}

# --- Database / APIs ---
DATABASE_URL="${process.env.DATABASE_URL || ''}"
NEXT_PUBLIC_API_URL="https://api.agencyos.com"
`;

    // Salvar o arquivo .env no novo diretório clonado
    const envFilePath = path.join(destinationPath, ".env.local");
    await fs.writeFile(envFilePath, envContent.trim());
    console.log(`[PROVISION] Variáveis de ambiente e DNA da marca injetados.`);

    // Opcional: Atualizar package.json do novo projeto com o novo "name"
    const packageJsonPath = path.join(destinationPath, "package.json");
    try {
      const pkgData = await fs.readFile(packageJsonPath, "utf-8");
      const pkgJson = JSON.parse(pkgData);
      pkgJson.name = slug;
      await fs.writeFile(packageJsonPath, JSON.stringify(pkgJson, null, 2));
    } catch {
      // Ignora se não houver package.json no template
    }

    console.log(`[PROVISION] Site de ${clientName} (${slug}) pronto para deploy. Tempo decorrido: Sub-minuto!`);
    
    return {
      success: true,
      tenantId: tenant.id,
      path: destinationPath,
    };
  }
}
